
// Not sorted
const oceanList = [
	"Pacific",
    "Atlantic",
    "Indian",
    "Southern",
    "Arctic",
];

const seaList = [
    "Philippine",
    "Coral",
    "American Mediterranean",
    "Arabian",
    "Sargasso",
    "South China",
    "Weddell",
    "Caribbean",
    "Mediterranean",
    "Gulf of Guinea",
    "Tasman",
    "Bay of Bengal",
    "Bering",
    "Sea of Okhotsk",
    "Gulf of Mexico",
    "Gulf of Alaska",
    "Barents",
    "Norwegian",
    "East China",
    "Hudson Bay",
    "Greenland",
    "Somov",
    "Mar de Grau",
    "RiiserLarsen",
    "Sea of Japan",
    "Argentine",
    "East Siberian",
    "Lazarev",
    "Kara",
    "Scotia",
    "Labrador",
    "Andaman",
    "Laccadive",
    "Irminger",
    "Solomon",
    "Mozambique Channel",
    "Cosmonauts",
    "Banda",
    "Baffin Bay",
    "Laptev",
    "Arafura",
    "Ross",
    "Chukchi",
    "Timor",
    "North",
    "Bellingshausen",
    "Beaufort",
    "Red",
    "Black",
    "Gulf of Aden",
    "Yellow",
    "Baltic",
    "Caspian",
    "Libyan",
    "Mawson",
    "Levantine",
    "Java",
    "Gulf of Thailand",
    "Celtic",
    "Gulf of Carpentaria",
    "Celebes",
    "Tyrrhenian",
    "Sulu",
    "Cooperation",
    "Persian Gulf",
    "Flores",
    "Gulf of Saint Lawrence",
    "Bay of Biscay",
    "Aegean",
    "Gulf of Anadyr",
    "Molucca",
    "Oman",
    "Ionian",
    "Gulf of California",
    "Balearic",
    "Adriatic",
];

module.exports = {
	oceanList,
    seaList,
};


